studyTab <- tabItem(
  tabName = "meta_study",
  h2("Study Metadata"),
  fluidRow(
    column(width = 4,
           box(
             width=NULL,
             title = "Select existing study",

             uiOutput("ui_cancer_study_identifier"),
             actionButton("upload", "Load study", class = "btn-success"),
             br(),br(),
             DT::DTOutput("studyTable")
           )
    ),
    column(width = 8,
           box(
             width=NULL,
             title = "Add new study",
             column(
               6,
               textInput("add_study_identifier",
                         label = "Add ID of cancer study",
                         placeholder = "e.g. brca_joneslab_2013"),
               textInput("add_study_name",
                         label = "Add name of cancer study",
                         placeholder = "e.g. Breast Cancer (Jones Lab 2013)"),
               textInput("add_short_name",
                         label = "Add short name of cancer study",
                         placeholder = "e.g. BRCA (Jones)"),
               uiOutput("ui_type_of_cancer"),
               actionButton("add_study", "Add study")
             ),
             column(
               6,
               textAreaInput(
                 "description",
                 label = "Add description of the cancer study",
                 height = "200px",
                 resize = "vertical",
                 placeholder = "Comprehensive profiling of 103 breast cancer samples. Generated by the Jones Lab 2013"
               )
             )
           ),
           box(
             width=NULL,
             title = "Alternatively select cancer type here",
             DT::DTOutput("oncotree_table")
           )
    )
  )
)
